name: My deploy Playwright to Azure Function

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'HttpPlaywright'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.10'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Playwright
      run: |
        python -m pip install playwright
        playwright install chromium

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
        scm-do-build-during-deployment: true
        enable-oryx-build: true
        python-version: ${{ env.PYTHON_VERSION }}
        worker-runtime: python
        app-settings: |
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
          PLAYWRIGHT_BROWSERS_PATH=/home/site/wwwroot/chromium-1097/chrome-linux/chrome
          
